### ISSUE TITLE
Edit Actions don't complete

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki#17] opened 2014-10-03 17:55 UTC
I'm seeing edit actions silently fail. This seems to be associated with large payloads like Factory plugin posting a dropped image. I believe the same root cause is in play for this report, an explicit fork of a remote page to the origin server that also silently fails. I've not seen the problem for images or forks using the ruby/sinatra server.

From the client side using Chrome's inspector the PUT hangs pending for four minutes and then eventually fails. The wiki-client code catches the failure and stores the remote page in browser local storage under the origin name. That's something, but not the desired result.

![image](https://cloud.githubusercontent.com/assets/12127/4509804/19d43758-4b24-11e4-9f5d-ed4e902241f9.png)

From the server side the express log doesn't show a PUT for some time. Presumably the PUT is in progress until jQuery ajax times out and closes the connection. jQuery tries several times over the four minute period. None of the express logs show any status code being returned.

![image](https://cloud.githubusercontent.com/assets/12127/4509902/f107ffc0-4b24-11e4-938a-5d96d03e9ad4.png)

The payload for this PUT (if I read Chrome's inspector correctly) is one url encoded line of 24399 characters.

I'm running wiki with one argument, -f. Wiki -v reports:

```
wiki: 0.3.5
wiki-server: 0.2.1
wiki-client: 0.2.12
wiki-plugin-activity: 0.1.1
wiki-plugin-bars: 0.1.3
wiki-plugin-bytebeat: 0.1.1
wiki-plugin-calculator: 0.1.3
wiki-plugin-calendar: 0.1.2
wiki-plugin-changes: 0.1.2
wiki-plugin-chart: 0.2.1
wiki-plugin-code: 0.1.1
wiki-plugin-data: 0.1.1
wiki-plugin-efficiency: 0.1.2
wiki-plugin-factory: 0.1.1
wiki-plugin-favicon: 0.1.1
wiki-plugin-federatedwiki: 0.1.1
wiki-plugin-force: 0.1.1
wiki-plugin-future: 0.1.1
wiki-plugin-html: 0.0.2
wiki-plugin-image: 0.1.1
wiki-plugin-line: 0.1.2
wiki-plugin-linkmap: 0.1.2
wiki-plugin-logwatch: 0.1.1
wiki-plugin-map: 0.1.3
wiki-plugin-mathjax: 0.1.1
wiki-plugin-metabolism: 0.1.1
wiki-plugin-method: 0.1.5
wiki-plugin-pagefold: 0.1.1
wiki-plugin-paragraph: 0.1.1
wiki-plugin-parse: 0.1.1
wiki-plugin-pushpin: 0.1.1
wiki-plugin-radar: 0.1.1
wiki-plugin-reduce: 0.1.1
wiki-plugin-reference: 0.1.1
wiki-plugin-report: 0.1.1
wiki-plugin-rollup: 0.1.1
wiki-plugin-scatter: 0.1.2
wiki-plugin-twadio: 0.1.2
wiki-plugin-txtzyme: 0.1.4
wiki-plugin-video: 0.1.1
```

The server is running on CentOS release 6.5 (Final). I've seen similar behavior running on Mac OS.

This would seem to be some protocol confusion between jQuery and Node.js. This seems unlikely so I am unsure of how to continue debugging. Suggestions welcome. Pull requests would be delightful.

**Comment by paul90** [comment] 2020-05-12 10:09
Closing this issue. Was most likely caused by the image squeeze not working, this was fixed in the latest client update - v0.20.2.

**Closed by paul90** 2020-05-12 10:09 UTC
